// SPDX-FileCopyrightText: 2026 Limen-Neural contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Delayed-reward association: synthetic, generated by this file, no external data.
//! A uses channels 0–1, B uses 2–3. Reward/omission labels are reversed for the
//! deterministic shuffled control; reward modulation disabled is a third control.
//! Two equal-share LIF neurons train for four episodes of four pairing ticks,
//! K = 8 intervening silent ticks, then a zero-stimulus payout (tau_eligibility =
//! 100). Episode resets clear traces/dopamine, never interrupt the delay.
//!
//! Caller-owned splits use trial IDs 0–3 (train), 100–107 (development), and
//! 200–207 (final), with disjoint stimulus-generator seeds. Final seeds are
//! [11, 29, 47, 71, 101]; development uses [1, 2, 3]. Each A/B pair shares an
//! amplitude; conditions share initialization, stimuli, and engine RNG streams.
//! Each readout uses independent checkpoint-derived runtime with all plasticity
//! bits retained and frozen. Original training checkpoints/RNGs stay untouched.
//!
//! Score D is class-conditional spike-rate discrimination: frozen spikes per
//! neuron per tick for A minus B. Every seed AND the aggregate must have
//! D_aligned >= 0.05 and D_aligned - D_shuffled >= 0.05. Training reward/weight
//! diagnostics cannot pass this test. The no-modulation control also checks
//! D == 0 as a symmetry invariant. The metric, seeds, split, and margin were
//! recorded before development; all parameters were locked before final scoring.
//! See docs/benchmarks/delayed-association.md and README.

use neuromod::{NeuroModulators, RmStdpConfig, SpikingNetwork};
use plasticity_lab::{
    EvaluationExample, EvaluationSummary, PlasticityTrainer, RewardMapping, TrainingConfig,
    TrainingExample,
};
use rand::{RngExt as _, SeedableRng, rngs::SmallRng};

const DELAY: usize = 8;
const PAIRING: usize = 4;
const READOUT: usize = 6;
const MARGIN: f64 = 0.05;
const FINAL_SEEDS: [u64; 5] = [11, 29, 47, 71, 101];

#[derive(Debug, PartialEq)]
struct Trial {
    id: usize,
    class: usize,
    amplitude: f32,
}

enum Condition {
    Aligned,
    Shuffled,
    ModulationDisabled,
}

fn trials(seed: u64, start: usize, count: usize, amplitude: f32) -> Vec<Trial> {
    // Independent split-specific stimulus RNG, never the engine's stream.
    let mut rng = SmallRng::seed_from_u64(seed ^ ((start as u64 + 1) << 32));
    (0..count / 2)
        .flat_map(|pair| {
            let first = usize::from(rng.random::<bool>());
            let amplitude = amplitude * rng.random_range(0.9..1.1);
            [first, 1 - first].map(|class| Trial {
                id: start + 2 * pair + usize::from(class != first),
                class,
                amplitude,
            })
        })
        .collect()
}

fn stimulus(trial: &Trial) -> Vec<f32> {
    let mut input = vec![0.0; 4];
    input[2 * trial.class..2 * trial.class + 2].fill(trial.amplitude);
    input
}

fn training_batch(trial: &Trial, shuffled: bool) -> Vec<TrainingExample> {
    (0..=PAIRING + DELAY)
        .map(|tick| TrainingExample {
            stimuli: if tick < PAIRING {
                stimulus(trial)
            } else {
                vec![0.0; 4]
            },
            reward: f32::from(tick == PAIRING + DELAY && (trial.class == 0) != shuffled),
        })
        .collect()
}

fn discrimination(classes: &[EvaluationSummary; 2]) -> f64 {
    let rate = |summary: &EvaluationSummary| {
        summary.total_spikes as f64
            / (summary.steps_processed * summary.per_neuron_spikes.len()) as f64
    };
    rate(&classes[0]) - rate(&classes[1])
}

fn initial_checkpoint() -> Vec<u8> {
    let mut network = SpikingNetwork::with_dimensions(2, 0, 4);
    network.set_rm_stdp_config(RmStdpConfig {
        tau_eligibility: 100.0,
        reward_lr: 8.0,
        ..RmStdpConfig::default()
    });
    for neuron in &mut network.neurons {
        neuron.weights.fill(0.5);
        neuron.threshold = 0.12;
    }
    serde_json::to_vec(&network).unwrap()
}

fn train_condition(
    checkpoint: &[u8],
    training: &[Trial],
    rng: &SmallRng,
    condition: Condition,
) -> (SpikingNetwork, SmallRng) {
    let mut network: SpikingNetwork = serde_json::from_slice(checkpoint).unwrap();
    assert_eq!(serde_json::to_vec(&network).unwrap(), checkpoint);
    let mut rng = rng.clone();
    let mut trainer = PlasticityTrainer::new(TrainingConfig {
        use_reward_modulation: !matches!(condition, Condition::ModulationDisabled),
        reward_mapping: RewardMapping::builder().dopamine_gain(1.0).build().unwrap(),
    });
    let shuffled = matches!(condition, Condition::Shuffled);
    for trial in training {
        // Episodic task: discard prior trial's traces and dopamine, retain weights
        // and thresholds. Never reset between pairing and delayed payout.
        network.reset();
        trainer
            .run_session_with_rng(&mut network, &training_batch(trial, shuffled), &mut rng)
            .unwrap();
    }
    (network, rng)
}

fn plasticity_bits(network: &SpikingNetwork) -> Vec<u32> {
    let mut bits = [
        network.modulators.dopamine,
        network.modulators.serotonin,
        network.modulators.acetylcholine,
        network.modulators.norepinephrine,
        network.stdp_config.tau_eligibility,
        network.stdp_config.reward_lr,
        network.stdp_config.w_min,
        network.stdp_config.w_max,
    ]
    .map(f32::to_bits)
    .to_vec();
    for neuron in &network.neurons {
        bits.extend([neuron.decay_rate, neuron.threshold, neuron.base_threshold].map(f32::to_bits));
        bits.extend(neuron.weights.iter().map(|w| w.to_bits()));
        bits.extend(
            neuron
                .eligibility
                .iter()
                .flat_map(|e| [e.value.to_bits(), e.tau.to_bits()]),
        );
    }
    bits
}

fn evaluate(trained: &SpikingNetwork, held_out: &[Trial], seed: u64) -> f64 {
    let checkpoint = serde_json::to_vec(trained).unwrap();
    let before = plasticity_bits(trained);
    let mut rng = SmallRng::seed_from_u64(seed ^ 0xE7A1_0000);
    let mut trainer = PlasticityTrainer::new(TrainingConfig::default());
    let mut classes: [EvaluationSummary; 2] = std::array::from_fn(|_| EvaluationSummary {
        per_neuron_spikes: vec![0; trained.neurons.len()],
        ..EvaluationSummary::default()
    });
    for trial in held_out {
        let mut evaluation: SpikingNetwork = serde_json::from_slice(&checkpoint).unwrap();
        // Start each readout with fresh runtime, not the last training class's
        // prediction/membrane history. reset() also clears traces/modulators;
        // restore those from the checkpoint to preserve *all* plasticity bits.
        evaluation.reset();
        evaluation.modulators = trained.modulators;
        for (target, source) in evaluation.neurons.iter_mut().zip(&trained.neurons) {
            target.eligibility.clone_from(&source.eligibility);
        }
        assert_eq!(plasticity_bits(&evaluation), before);
        let data = vec![
            EvaluationExample {
                stimuli: stimulus(trial)
            };
            READOUT
        ];
        let summary = trainer
            .run_eval_with_rng(
                &mut evaluation,
                &data,
                &NeuroModulators::default(),
                &mut rng,
            )
            .unwrap();
        assert_eq!(plasticity_bits(&evaluation), before);
        assert_eq!(evaluation.global_step, READOUT as i64);
        assert!(evaluation.predictive_state.iter().any(|p| *p > 0.0));
        let class = &mut classes[trial.class];
        class.steps_processed += summary.steps_processed;
        class.total_spikes += summary.total_spikes;
        for (total, count) in class
            .per_neuron_spikes
            .iter_mut()
            .zip(summary.per_neuron_spikes)
        {
            *total += count;
        }
    }
    assert_eq!(serde_json::to_vec(trained).unwrap(), checkpoint);
    discrimination(&classes)
}

fn paired_scores(seed: u64, split_start: usize) -> [f64; 3] {
    let initial = initial_checkpoint();
    let training = trials(seed, 0, 4, 0.8);
    let held_out = trials(seed, split_start, 8, 0.15);
    let rng = SmallRng::seed_from_u64(seed);
    let (aligned, aligned_rng) = train_condition(&initial, &training, &rng, Condition::Aligned);
    let (shuffled, shuffled_rng) = train_condition(&initial, &training, &rng, Condition::Shuffled);
    let (disabled, disabled_rng) =
        train_condition(&initial, &training, &rng, Condition::ModulationDisabled);
    assert_eq!(aligned_rng, shuffled_rng);
    assert_eq!(aligned_rng, disabled_rng);
    let before_rngs = [
        aligned_rng.clone(),
        shuffled_rng.clone(),
        disabled_rng.clone(),
    ];
    let scores = [
        evaluate(&aligned, &held_out, seed),
        evaluate(&shuffled, &held_out, seed),
        evaluate(&disabled, &held_out, seed),
    ];
    assert_eq!([aligned_rng, shuffled_rng, disabled_rng], before_rngs);
    scores
}

#[test]
fn association_delayed_reward_beats_paired_shuffled_on_frozen_holdout() {
    // Print every seed and the aggregate BEFORE asserting the learning criterion,
    // so failures cannot hide unfavorable rows. Never tune using this split.
    let rows = FINAL_SEEDS.map(|seed| paired_scores(seed, 200));
    let mean: [f64; 3] = std::array::from_fn(|i| {
        rows.iter().map(|scores| scores[i]).sum::<f64>() / rows.len() as f64
    });
    println!("seed aligned_D shuffled_D disabled_D paired_advantage");
    for (seed, [aligned, shuffled, disabled]) in FINAL_SEEDS.iter().zip(rows) {
        println!(
            "{seed} {aligned:.6} {shuffled:.6} {disabled:.6} {:.6}",
            aligned - shuffled
        );
    }
    println!(
        "mean {:.6} {:.6} {:.6} {:.6}",
        mean[0],
        mean[1],
        mean[2],
        mean[0] - mean[1]
    );
    for (index, [aligned, shuffled, disabled]) in rows.into_iter().chain([mean]).enumerate() {
        assert!(
            aligned >= MARGIN,
            "row {index}: aligned D={aligned} < {MARGIN}"
        );
        assert!(
            aligned - shuffled >= MARGIN,
            "row {index}: paired advantage={} < {MARGIN}",
            aligned - shuffled
        );
        assert_eq!(disabled, 0.0, "row {index}: neutral no-modulation control");
    }
}

#[test]
fn association_development_replays_training_and_frozen_readout() {
    let initial = initial_checkpoint();
    let training = trials(1, 0, 4, 0.8);
    let rng = SmallRng::seed_from_u64(1);
    let (first, first_rng) = train_condition(&initial, &training, &rng, Condition::Aligned);
    let (second, second_rng) = train_condition(&initial, &training, &rng, Condition::Aligned);
    assert_eq!(
        serde_json::to_vec(&first).unwrap(),
        serde_json::to_vec(&second).unwrap()
    );
    assert_eq!(first_rng, second_rng);
    assert!(
        first
            .neurons
            .iter()
            .flat_map(|n| &n.eligibility)
            .any(|e| e.value != 0.0)
    );
    for seed in [1, 2, 3] {
        let scores = paired_scores(seed, 100);
        println!("development seed={seed}: {scores:?}");
        assert_eq!(scores, paired_scores(seed, 100));
        assert!(scores[0] >= MARGIN && scores[0] - scores[1] >= MARGIN);
        assert_eq!(scores[2], 0.0);
    }
}

#[test]
fn association_banks_credit_until_the_silent_delayed_payout() {
    let initial = initial_checkpoint();
    let mut network: SpikingNetwork = serde_json::from_slice(&initial).unwrap();
    let trial = Trial {
        id: 0,
        class: 0,
        amplitude: 0.8,
    };
    let batch = training_batch(&trial, false);
    let mut rng = SmallRng::seed_from_u64(1);
    let mut trainer = PlasticityTrainer::new(
        TrainingConfig::default()
            .with_reward_mapping(RewardMapping::builder().dopamine_gain(1.0).build().unwrap()),
    );
    trainer
        .run_session_with_rng(&mut network, &batch[..PAIRING + DELAY], &mut rng)
        .unwrap();
    assert_eq!(network.global_step, (PAIRING + DELAY) as i64);
    for neuron in &network.neurons {
        assert_eq!(neuron.weights, vec![0.5; 4], "no reward has arrived");
        assert!(neuron.eligibility[..2].iter().any(|e| e.value > 0.0));
    }
    assert!(
        network
            .input_spike_times
            .iter()
            .all(|t| *t <= PAIRING as i64)
    );
    trainer
        .run_session_with_rng(&mut network, &batch[PAIRING + DELAY..], &mut rng)
        .unwrap();
    assert!(
        network
            .neurons
            .iter()
            .any(|n| n.weights[0] + n.weights[1] > 1.0)
    );
    // Weight contrast is a protocol diagnostic, never the held-out score.
}

/// Check one episode's stimuli/delay/payout and return both conditions' payouts.
fn assert_delayed_labels(trial: &Trial) -> [f32; 2] {
    let aligned = training_batch(trial, false);
    let shuffled = training_batch(trial, true);
    assert_eq!(aligned.len(), PAIRING + DELAY + 1);
    assert_eq!(aligned.len(), shuffled.len());
    let expected_stimulus = if trial.class == 0 {
        vec![trial.amplitude, trial.amplitude, 0.0, 0.0]
    } else {
        vec![0.0, 0.0, trial.amplitude, trial.amplitude]
    };
    let expected_payout = if trial.class == 0 {
        (1.0, 0.0)
    } else {
        (0.0, 1.0)
    };
    for (tick, (a, s)) in aligned.iter().zip(&shuffled).enumerate() {
        assert_eq!(a.stimuli, s.stimuli);
        assert_eq!(a.stimuli.len(), 4);
        if tick < PAIRING {
            assert_eq!(a.stimuli, expected_stimulus);
        } else {
            assert_eq!(a.stimuli, vec![0.0; 4]);
        }
        if tick < PAIRING + DELAY {
            assert_eq!((a.reward, s.reward), (0.0, 0.0));
        } else {
            assert_eq!((a.reward, s.reward), expected_payout);
        }
    }
    [
        aligned[PAIRING + DELAY].reward,
        shuffled[PAIRING + DELAY].reward,
    ]
}

#[test]
fn association_protocol_pairs_inputs_and_permutes_only_delayed_labels() {
    let training = trials(1, 0, 4, 0.8);
    assert_eq!(training.len(), 4);
    for pair in training.as_chunks::<2>().0 {
        assert_ne!(pair[0].class, pair[1].class);
        assert_eq!(pair[0].amplitude, pair[1].amplitude);
    }
    let mut rewards = [Vec::new(), Vec::new()];
    for trial in &training {
        let [aligned, shuffled] = assert_delayed_labels(trial);
        rewards[0].push(aligned);
        rewards[1].push(shuffled);
    }
    for reward in &mut rewards {
        reward.sort_by(f32::total_cmp);
        assert_eq!(reward, &[0.0, 0.0, 1.0, 1.0]);
    }
}

#[test]
fn association_split_is_disjoint_and_seeded() {
    let training = trials(1, 0, 4, 0.8);
    assert_eq!(training, trials(1, 0, 4, 0.8));
    assert_ne!(training, trials(2, 0, 4, 0.8));
    let development = trials(1, 100, 8, 0.15);
    let held_out = trials(1, 200, 8, 0.15);
    assert_eq!((development.len(), held_out.len()), (8, 8));
    for (left, right) in [
        (&training, &development),
        (&training, &held_out),
        (&development, &held_out),
    ] {
        assert!(left.iter().all(|l| right.iter().all(|r| l.id != r.id)));
    }
}

#[test]
fn association_score_uses_class_conditional_frozen_spike_rates() {
    // Unequal exposures catch a shared denominator; two neurons catch omission
    // of the population normalization. A = 6/(4*2), B = 2/(8*2).
    let classes = [
        EvaluationSummary {
            steps_processed: 4,
            total_spikes: 6,
            per_neuron_spikes: vec![4, 2],
        },
        EvaluationSummary {
            steps_processed: 8,
            total_spikes: 2,
            per_neuron_spikes: vec![1, 1],
        },
    ];
    assert_eq!(discrimination(&classes), 0.625);
    assert_eq!(
        discrimination(&[classes[1].clone(), classes[0].clone()]),
        -0.625
    );
}
